#!/usr/bin/env -S ansible-playbook -vvv -K
- hosts: localhost
  connection: local
  tasks:
    - name: remove apt packages
      apt:
        name:
          - aisleriot
          - libreoffice-draw
          - libreoffice-impress
          - gnome-mahjongg
          - gnome-mines
          - gnome-sudoku
          - gnome-todo
          - rhythmbox
          - simple-scan
          - thunderbird
        state: absent
      become: true
