#!/usr/bin/env -S ansible-playbook -vvv -K
- hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      apt:
        name:
          - alacarte
          - anki
          - chromium-browser
          - chrome-gnome-shell
          - curl
          - docker.io
          - emacs
          - flameshot
          - flatpak
          - geary
          - git
          - gitk
          - gnome-software-plugin-flatpak
          - gthumb
          - htop
          - keepassxc
          - libpq-dev
          - meld
          - nodejs
          - npm
          - postgresql-client
          - python3
          - python-dev
          - python3-pip
          - ripgrep
          - rofi
          - rsync
          - solaar
          - stow
          - telegram-desktop
          - vim
          - xdotool
          - xsel
      become: true
