#!/usr/bin/env -S ansible-playbook -vvv -K
- hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      apt:
        name:
          - alacarte
          - atom
          - brave-browser
          - chromium-browser
          - chrome-gnome-shell
          - curl
          - docker.io
          - emacs
          - flatpak
          - geary
          - git
          - gnome-software-plugin-flatpak
          - htop
          - keepassxc
          - postgresql-client
          - python3
          - python3-pip
          - ripgrep
          - rofi
          - solaar
          - telegram-desktop
          - typora
          - xdotool
          - xsel
      become: true
