#!/usr/bin/env -S ansible-playbook -vvv
- hosts: localhost
  connection: local
  tasks:
    - name: install pip packages
      pip:
        executable: '/usr/bin/pip3'
        extra_args: --user -U
        name:
          - aiohttp
          - browsercookie
          - docker
          - docker-compose
          - fire
          - ipdb
          - ipython
          - jupyter
          - pre-commit
          - psycopg2
          - pynput
          - pyparsing
          - pyppeteer
          - pyquery
          - ruamel.yaml
          - safeeyes
          - yeelight
