#!/usr/bin/env -S ansible-playbook -K --step
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: add apt keys
      apt_key:
        url: '{{ item }}'
      with_items:
        - https://typora.io/linux/public-key.asc
        - https://packagecloud.io/AtomEditor/atom/gpgkey
      become: true
      tags: apt, repository

    - name: add apt repositories
      apt_repository:
        repo: '{{ item }}'
      with_items:
        - 'deb https://typora.io/linux ./'
        - 'deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main'
      become: true
      tags: apt, repository

    - name: update apt
      apt:
        update_cache: yes
        upgrade: true
        autoclean: true
        autoremove: true
      become: true
      tags: apt

    - name: install apt packages
      apt:
        name:
          - atom
          - emacs-gtk
          - hub
          - python-ldtp
          - python3
          - typora
          - zsh
      become: true
      tags: apt, apt-get

    - name: install deb packages
      apt:
        deb: '{{ item }}'
      with_items:
        - https://atom.io/download/deb
      become: true
      tags: deb

    - name: install appimage applications
      get_url:
        url: '{{ item }}'
        dest: ~/Applications
        mode: 0744
      with_items:
        - 'https://bintray.com/colinduquesnoy/MellowPlayer/download_file?file_path=stable/3.5.0%2FMellowPlayer-x86_64.AppImage'
      tags: appimage

    - name: install pip packages
      pip:
        executable: '/usr/bin/pip3'
        extra_args: --user
        name:
          - aiohttp
          - browsercookie
          - flask
          - jupyter
          - mypy
          - mypy_extensions
          - notebook
          - Pillow
          - pylint
          - pytype
          - pyppeteer
          - python-dotenv
          - pyquery
          - redis
          - sh
          - uncurl
          - yeelight
          - xonsh
          - django
          - nest_asyncio
          - motor
          - motor
          - feedparser
          - feedreader
          - aiohttp
      tags: pip
