#!/usr/bin/env -S ansible-playbook -K --tags=apt #-get
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - apt_key:
        url: '{{ item }}'
      with_items:
        - https://typora.io/linux/public-key.asc
      become: true
      tags: apt, repository

    - apt_repository:
        repo: '{{ item }}'
      with_items:
        - 'deb https://typora.io/linux ./'
        - 'ppa:bablu-boy/nutty'
        - 'deb https://www.charlesproxy.com/packages/apt/ charles-proxy main'
      become: true
      tags: apt, repository

    - apt:
        update_cache: yes
        upgrade: true
        autoclean: true
        autoremove: true
      become: true
      tags: apt

    - apt:
        name:
          - charles-proxy
          - com.github.babluboy.nutty
          - emacs-gtk
          - python3
          - typora
          - hub
          - python-ldtp
      become: true
      tags: apt, apt-get

    - name: appimage
      get_url:
        url: '{{ item }}'
        dest: ~/Applications
        mode: 0744
      with_items:
        - 'https://bintray.com/colinduquesnoy/MellowPlayer/download_file?file_path=stable/3.5.0%2FMellowPlayer-x86_64.AppImage'
      tags: appimage

    - pip:
        executable: '/usr/bin/pip3'
        extra_args: --user
        name:
          - aiohttp
          - browsercookie
          - flask
          - jupyter
          - mypy
          - mypy_extensions
          - notebook
          - Pillow
          - pylint
          - pytype
          - pyppeteer
          - python-dotenv
          - pyquery
          - redis
          - sh
          - uncurl
          - yeelight
          - xonsh
          - django
          - nest_asyncio
          - motor
          - motor
          - feedparser
          - feedreader
          - aiohttp
      tags: pip
