#!/usr/bin/env -S ansible-playbook -K --step
- hosts: localhost
  connection: local
  vars:
    user: c6401
  tasks:
    - name: crontab
      block:
        - name: brightness down at 0:30
          cron:
            name: brightness down
            minute: 30
            hour: 0
            job: echo 20 > /sys/class/backlight/intel_backlight/brightness
          become: true

        - name: shutdown at 2
          cron:
            name: shutdown at 2
            minute: 0
            hour: 2
            job: shutdown -h now
          become: true

        - name: dark theme at 22
          cron:
            name: dark theme
            minute: 0
            hour: 22
            job: '/usr/bin/env DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$(pgrep gnome-session)/environ|cut -d= -f2-) gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark'

        - name: light theme at 6
          cron:
            name: light theme
            minute: 0
            hour: 6
            job: '/usr/bin/env DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$(pgrep gnome-session)/environ|cut -d= -f2-) gsettings set org.gnome.desktop.interface gtk-theme Adwaita'

    - name: link dropbox pictures
      file:
        src: ~/Dropbox/Photos
        dest: ~/Pictures
        state: link
        force: true

    - name: install spacemacs
      git:
        repo: 'https://github.com/syl20bnr/spacemacs'
        dest: '~/.emacs.d'
        version: develop

    - name: docker user
      user:
        name: '{{ user }}'
        groups: docker
        append: true
      become: true

    - name: install vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim

    - name: no telemetry in vscode
      lineinfile:
        insertafter: '^{'
        line: '    {{ item }}'
        path:  ~/.config/Code/User/settings.json
      with_items:
        - '"telemetry.enableCrashReporter": false,'
        - '"telemetry.enableTelemetry": false,'

    - name: zsh
      block:
        - name: install oh my zsh
          git:
            repo: https://github.com/robbyrussell/oh-my-zsh.git
            dest: ~/.oh-my-zsh

        - name: copy oh my zsh rc file
          copy:
            src: ~/.oh-my-zsh/templates/zshrc.zsh-template
            dest: ~/.zshrc
